version: '3.4'

services:
  lswebapidappermysql:
    image: ${DOCKER_REGISTRY-}lswebapidappermysql
    build:
      context: .
      dockerfile: LSWebApiDapperMySql/Dockerfile

  mysql-host:
    image: mysql
    volumes:
      - data_base:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "Loja"
    networks:
      - databases
      
volumes:  
  data_base:

networks: 
    databases:
      driver: bridge